### ISSUE TITLE
Foundation Umbrella icon broken

### ISSUE THREAD

**Issue by Quitch** [Thalassocracy/Planetary-Annihilation-Subfactions-Mod#6]
![386070_20180902105632_1](https://user-images.githubusercontent.com/5182715/44954750-1a5aee00-ae9f-11e8-8f9a-e003be5c2c5d.png)

I don't see anything wrong with the file.

This was based on the latest testing1

**Comment by quildtide** [comment]
file in icon_atlas/img was missing; fixed
