### ISSUE TITLE
Heal Drone missing bone

### ISSUE THREAD

**Issue by Quitch** [Thalassocracy/Planetary-Annihilation-Subfactions-Mod#7]
ERROR Unable to find bone [bone_turret] for build arm [/pa/units/foundation/orbital/heal_drone_tool.json] on unit [/pa/units/foundation/orbital/heal_drone.json]

You need to make sure your server logs are clean.

**Comment by quildtide** [comment]
resolved.

Server logs are not showing any errors for me, for some reason.

I may be looking at the wrong logs. These are the logs located in Local\Uber Entertainment\Planetary Annihilation, yes?

**Comment by Quitch** [comment]
I was running a server with --enable-crash-reporting --ai-log --disable-replays --game-mode PAExpansion1:Config --mt-enabled --server-name local --allow-lan --headless

While the logs for that would appear in a slightly different location, this particular error is unrelated to --ai-log AFAIK, so it should appear in yours.
